### get product

GET http://localhost:8080/api/v2/product HTTP/1.1


### get product with Token
GET http://localhost:8080/api/v2/product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjA3MjYzMzcsImlkIjoxLCJsZXZlbCI6Im5vcm1hbCIsInVzZXJuYW1lIjoiYWRtaW4ifQ.EuM-H2OIP4BnmB9v6wasNFGgu5YeVFMUSkgfJxm6IM4


### get product with keyword
GET http://localhost:8080/api/v2/product?keyword=edit HTTP/1.1


### get product by ID
GET http://localhost:8080/api/v2/product/2 HTTP/1.1


### create
POST http://localhost:8080/api/v2/product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjA3MjYzMzcsImlkIjoxLCJsZXZlbCI6Im5vcm1hbCIsInVzZXJuYW1lIjoiYWRtaW4ifQ.EuM-H2OIP4BnmB9v6wasNFGgu5YeVFMUSkgfJxm6IM4
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name";

React Test
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock";

300
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price";

180
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/png

< ./test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Edit

PUT http://localhost:8080/api/v2/product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjA3MjYzMzcsImlkIjoxLCJsZXZlbCI6Im5vcm1hbCIsInVzZXJuYW1lIjoiYWRtaW4ifQ.EuM-H2OIP4BnmB9v6wasNFGgu5YeVFMUSkgfJxm6IM4
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="id";

4
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name";

Angular Test Edit
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock";

3000
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price";

1800
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/png

< ./test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--