### get transaction

GET http://localhost:8080/api/v2/transaction HTTP/1.1

### create transaction
POST http://localhost:8080/api/v2/transaction HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjI2MzM5NTksImlkIjoyLCJsZXZlbCI6Im5vcm1hbCIsInVzZXJuYW1lIjoianIifQ.mFk4NZE5qAb66lq9UAme7NII84S4MfwvsCNXaPxoGaM
Content-Type: application/json

{
  "total": 700,
  "paid": 100,
  "change": 600,
  "payment_type": "cash",
  "payment_detail": "full",
  "order_list": "[]"
}